-- =========================================================================
-- Migración 0002: vínculo entre Supabase Auth y la tabla `usuarios`
-- =========================================================================
-- NOTA DE HISTORIAL: esta migración originalmente creaba un trigger que
-- vinculaba automáticamente cada usuario nuevo de Supabase Auth con una
-- fila en `usuarios`, tomando el rol de los metadatos con los que se
-- crea el usuario. En la práctica, el formulario "Add user" del panel de
-- Supabase no siempre permite cargar esos metadatos, y el trigger llegó
-- a bloquear la creación de usuarios directamente. Se decidió reemplazar
-- ese enfoque automático por uno manual, más simple y más confiable
-- (ver instrucciones en el README, sección "Crear usuarios"). Esta
-- migración queda vacía a propósito, y la corrección real está en
-- 0003_fix_trigger_usuarios.sql (que elimina el trigger si llegó a
-- crearse en un proyecto que ya corrió la versión anterior de este
-- archivo).
